networks:
  backend:
    driver: bridge

services:
  ytdownloader:
    image: thanhlam00290/yt-downloader:latest
    container_name: ytdownloader
    restart: unless-stopped
    ports:
      - "5000:5000"
    # volumes:
    #   - ./downloads:/app/download
    environment:
      FLASK_ENV: production
      PORT: 5000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 3s
    networks:
      - backend

  forwarder:
    image: thanhlam00290/forwarder:latest
    container_name: forwarder
    restart: unless-stopped
    depends_on:
      ytdownloader:
        condition: service_healthy
    environment:
      URL_FORWARD: "http://ytdownloader:5000"
      FIREBASE_DB_URL: "https://xxx.firebaseio.com"
    networks:
      - backend