version: "3.8"

services:
  ytdownloader:
    image: thanhlam00290/yt-downloader:latest
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./downloads:/app/downloads
    environment:
      - FLASK_ENV=production